language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .yaks-ci.sh
env:
    global:
    - DEPOPTS="lwt dune logs fmt cmdliner cmdliner ppx_deriving uuidm yojson lwt_ppx lwt_log ppx_cstruct atdgen"
    - PINS="apero-core:. apero-net:."
    - PACKAGE=apero 
    matrix:
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.06
